
branches:
  only:
    - master
    - fix_build_errors

language: python

python:
  - 3.3
  - 3.4
  - 3.5

install:
  - sudo add-apt-repository ppa:travis-ci/sqlite3 -y
  - pip install -r requirements.txt
  - pip install coverage coveralls

script:
  - coverage run --source=spkrepo setup.py test

after_success:
  - coveralls
