"""Add fs_uniquifier

Revision ID: 76d559b4e873
Revises: d429595e8362
Create Date: 2022-10-24 09:31:01.814928

"""
revision = "76d559b4e873"
down_revision = "d429595e8362"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("fs_uniquifier", sa.String(length=255), nullable=False)
    )
    op.create_unique_constraint(None, "user", ["fs_uniquifier"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "fs_uniquifier")
    # ### end Alembic commands ###
